#!/bin/bash

echo -e "Effacement des anciens fichiers temporaires...\n"

rm -f /tmp/newvno
rm -f /tmp/D201*.sql
rm -f /tmp/0991*.sql
rm -f /tmp/rtvoip[1-2]-interfaces
rm -f /tmp/rtvoip[1-2]-sipad
rm -f /tmp/pcscf[1-2]-interfaces
rm -f /tmp/req_sql_gwvoip
rm -f /tmp/count_sql_gwvoip1
rm -f /tmp/count_sql_gwvoip2

ssh si-erp-gestion-1 "rm -f /tmp/newvno"
ssh scscf-1-cbv1 "rm -f /tmp/D201*.sql"
ssh scscf-1-cbv2 "rm -f /tmp/D201*.sql"
ssh scscf-1-cbv1 "rm -f /tmp/req_sql_gwvoip"
ssh scscf-1-cbv2 "rm -f /tmp/req_sql_gwvoip"

ssh pcscf-2-cbv2 "rm -f /tmp/0991*.sql"

echo -e "nettoyage terminé !\n"
