#! /bin/sh
#


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC=lisos-autoinstall
NAME=lisos-autoinstall


case "$1" in
  start)
	echo -n "Starting $DESC: "
		lisos-pxe
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
