export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export RAILS_ENV=production

alias be='bundle exec'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
