#!/bin/bash
MAX_SECTORS="64"
NR_REQUESTS="512"
SCHEDULER="deadline"
BLOCKDEV="4096"
for device in /sys/block/sd*
do
    echo $MAX_SECTORS > $device/queue/max_sectors_kb
    echo $NR_REQUESTS > $device/queue/nr_requests
    echo $SCHEDULER > $device/queue/scheduler
done
for device in /dev/iscsi_*
do 
    /sbin/blockdev --setra $BLOCKDEV $device
done
exit 0
