#!/bin/bash
usage () {
  echo "usage : ${0} -h hostname [-d domain] [-i ip] [-t]" >&2
}

[ -z ${2} ] && {
  usage
  exit -1
}

while getopts :d:h:i:t opt
do
  case ${opt} in
    h)  hostname=${OPTARG}
    ;;
    d)  domain=${OPTARG}
    ;;
    i)  ip=${OPTARG}
    ;;
    t)  environment="development"
    ;; 
    '?')  echo "${0} : option ${OPTARG} is not valid" >&2
          usage
          exit -1
    ;;
  esac
done

if [ -z ${hostname} ]
then
  echo "You have to specified a hostname or realhostname"
  usage
  exit -1
fi

domain=${domain:-admin.alphalink.fr}
gold_server=${gold_server:-gold}
realhostname="${hostname}.${domain}"
ssldir=/var/lib/puppet/ssl
tmpfile=/tmp/puppetize.tmp.$$
environment=${environment:-production}
manifest="/var/lib/puppet/branches/${environment}/master/manifests/site.pp"
modulepath="/var/lib/puppet/branches/${environment}/modules/"
manifestdir="/var/lib/puppet/branches/${environment}/master/manifests/"
templatedir="/var/lib/puppet/branches/${environment}/master/templates"

# Si une ip est fournit, on l'utilise pour se connecter a l'hote via ssh
if [ ! -z ${ip} ]; then
    hostname=${ip}
fi

ssh -x ${hostname} <<EOF
sed -i 's/gold-ng/gold/g' /etc/apt/sources.list
sed -i 's/gold-ng/gold/g' /etc/puppet/puppet.conf
rm /etc/puppet/puppet.conf
aptitude update
aptitude -y install puppet/update facter/update
/etc/init.d/puppet stop
update-rc.d puppet stop 2 3 4 5 .
EOF

ssh -x ${hostname} "wget -O - http://${gold_server}.alphalink.fr/ALPHALINK.GPG | apt-key add -"

ssh root@${gold_server}.alphalink.fr "puppetca --generate '${realhostname}'"
ssh root@${gold_server}.alphalink.fr "tar cvf - ${ssldir}/certs/ca.pem ${ssldir}/certs/${realhostname}.pem ${ssldir}/private_keys/${realhostname}.pem" \
    | ssh -o "StrictHostKeyChecking no" root@${hostname} "tar xvf - -C /"
ssh root@${gold_server}.alphalink.fr "rm -f  ${ssldir}/certs/${realhostname}.pem ${ssldir}/private_keys/${hostname}.pem"

ssh root@${hostname} "puppetd --verbose --test --server ${gold_server}.alphalink.fr --ssldir /var/lib/puppet/ssl --fqdn=${realhostname} --manifest ${manifest} --modulepath ${modulepath} --manifestdir ${manifestdir} --templatedir ${templatedir} --environment ${environment}"
