#! /bin/sh
### BEGIN INIT INFO
# Provides:          slony1_update_lock_file
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Refresh /var/lock/slony1/opensips.lock
# Description:       /var/locl/slony1/opensips.lock is used
#                    to know when unlock locations tables
#                    on secondary PCSCF when it become master.
#                    This file may be missing after reboot.
### END INIT INFO

. /lib/lsb/init-functions

do_start () {
	if [ -f "/var/lock/slony1/opensips.lock" ] ; then
    echo "Lock file already exists"
    return 0
  else
    if /usr/bin/psql -U opensips opensips -h localhost -c '\d location' | grep -q '_pgsql_cluster.denyaccess'; then 
      echo "Lock file should exists, recreating it"
      touch /var/lock/slony1/opensips.lock && return 0
      return 1
    else
      echo "Local postgresql is master, no lock file need to be created"
      return 0
    fi
  fi
}

do_status () {
	if [ -f "/var/lock/slony1/opensips.lock" ] ; then
		return 0
	else
		return 1
	fi
}

case "$1" in
  start|"")
    do_start
	;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 1
	;;
  stop)
    # No-op
	;;
  status)
    do_status
    exit $?
	;;
  *)
	echo "Usage: slony1_update_lock_file [start|stop|status]" >&2
	exit 1
	;;
esac
