#!/bin/bash
name="apt-cacher-ng"
directory="/var/cache/$name"
filesystem="xfs"
vg_name=`vgdisplay -c | cut -d : -f 1 | sed 's/^ *//g'`
lv_path="/dev/$vg_name/$name"
lvcreate -L 20G -n $name $vg_name || exit -1
mkfs.xfs $lv_path || exit -2
mkdir -p $directory || exit -3
chown $name:$name $directory
echo "$lv_path $directory $filesystem defaults 0 2" >> /etc/fstab || exit -4
mount $directory || exit -5
