#!/bin/bash
ISCSIADM="/usr/bin/iscsiadm"
#MAX_SECTORS="64"
#NR_REQUESTS="512"
#SCHEDULER="deadline"
#BLOCKDEV="4096"
MAX_SECTORS="512"
NR_REQUESTS="128"
SCHEDULER="cfq"
BLOCKDEV="256"
PORTAL="169.254.62.101"

usage () {
   echo "Script destiné a monter une target iscsi depuis les san"
   echo "usage $0 -h target [-c] [-d]"
   echo "  -c : connect"
   echo "  -d : disconnect"
}

discover_iqn () {
  case $hostname in 
    "backup-1-jes")         hostname="backup-jes";;
    "proxy-2-sigma")        hostname="domu-2-proxy-sigma";;
    "proxy-3-sigma")        hostname="domu-3-proxy-sigma";;
    "proxy-1-d2i")          hostname="proxy-d2i";;
    "proxy-1-sopap")        hostname="proxy-sopap";;
    "vserver-1-sigma")      hostname="domu-1-nagios-sigma";;
    "vserver-1-qostelecom") hostname="domu-1-qostelecom";;
    "vserver-2-qostelecom") hostname="domu-2-qostelecom";;
  esac
  target=$($ISCSIADM -m discovery -t st -p $PORTAL | grep -oE "iqn.*$hostname$")
  if [ $? -ne 0 ]
  then
     echo "la target $hostname n'existe pas"
     exit -2
  fi
}

connect () {
  discover_iqn
  $ISCSIADM -m node -T $target -p $PORTAL -l
  for device in /sys/block/sd*
  do
    echo $MAX_SECTORS > $device/queue/max_sectors_kb
    echo $NR_REQUESTS > $device/queue/nr_requests
    echo $SCHEDULER > $device/queue/scheduler
  done

  until [ -b /dev/iscsi_$hostname ]
  do
    sleep 1
  done 

  for device in /dev/iscsi_$hostname*
  do 
    /sbin/blockdev --setra $BLOCKDEV $device
  done
}

disconnect () {
  discover_iqn
  $ISCSIADM -m node -T $target -p $PORTAL -u
}


while getopts :h:cd opt
do
  case ${opt} in
    h)  hostname=${OPTARG}
    ;;
    d)  disconnect
    ;;
    c)  connect
    ;;
    '?')  echo "${0} : option ${OPTARG} is not valid" >&2
      usage
      exit -1
    ;;
  esac
done

if [ -z $2 ]
then
  usage
  exit -3
fi

exit 0
