syntax on
set hlsearch
set ignorecase
set background=dark
" indentation
set autoindent
set shiftwidth=2
set tabstop=2
set expandtab
" copie à la souris
"set paste 
if has("autocmd")
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

if has("autocmd")
    filetype plugin indent on
endif

