#!/bin/sh

### BEGIN INIT INFO
# Provides:        jboss-as
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start JBoss AS7
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

# Load Java configuration.
[ -r /etc/java/java.conf ] && . /etc/java/java.conf
export JAVA_HOME

# Load JBoss AS init.d configuration.
if [ -z "$JBOSS_CONF" ]; then
  JBOSS_CONF="/etc/default/jboss-as"
fi

[ -r "$JBOSS_CONF" ] && . "${JBOSS_CONF}"

# Set defaults.

if [ -z "$JBOSS_HOME" ]; then
  JBOSS_HOME=/usr/share/jboss-as
fi
export JBOSS_HOME

if [ -z "$JBOSS_MODE" ]; then
  JBOSS_MODE=standalone
fi 

if [ -z "$JBOSS_PIDFILE" ]; then
  JBOSS_PIDFILE=/var/run/jboss-as/jboss-as.pid
fi
export JBOSS_PIDFILE

if [ -z "$STARTUP_WAIT" ]; then
  STARTUP_WAIT=30
fi

if [ -z "$SHUTDOWN_WAIT" ]; then
  SHUTDOWN_WAIT=30
fi

if [ -z "$JBOSS_CONFIG" ]; then
  JBOSS_CONFIG=standalone.xml
fi

if [ -z "$JBOSS_USER" ]; then
  JBOSS_USER=root
fi

JBOSS_SCRIPT=$JBOSS_HOME/bin/$JBOSS_MODE.sh

prog='jboss-as'

start() {
  log_daemon_msg "Starting JBoss AS7" "jboss-as"
  if [ -f $JBOSS_PIDFILE ]; then
    read ppid < $JBOSS_PIDFILE
    [ `ps --pid $ppid 2> /dev/null | grep -c $ppid 2> /dev/null` -eq '1' ] || rm -f $JBOSS_PIDFILE
  fi
  mkdir -p $(dirname $JBOSS_PIDFILE)
  chown $JBOSS_USER $(dirname $JBOSS_PIDFILE)

  LAUNCH_JBOSS_IN_BACKGROUND=1 JBOSS_PIDFILE=$JBOSS_PIDFILE start-stop-daemon --start --oknodo --background --pidfile $JBOSS_PIDFILE --startas $JBOSS_SCRIPT --user $JBOSS_USER --chuid $JBOSS_USER -- -c $JBOSS_CONFIG
  log_end_msg $?
}

stop() {
  log_daemon_msg "Stopping JBoss AS7" "jboss-as"

  start-stop-daemon --stop --retry $SHUTDOWN_WAIT --pidfile $JBOSS_PIDFILE
  log_end_msg $?
  rm -f $JBOSS_PIDFILE
}

status() {
  status_of_proc -p $JBOSS_PIDFILE $prog "JBoss AS7"
}

case "$1" in
  start)
      start
      ;;
  stop)
      stop
      ;;
  restart)
      $0 stop
      $0 start
      ;;
  status)
      status
      ;;
  *)
      ## If no parameters are given, print which are avaiable.
      echo "Usage: $0 {start|stop|status|restart}"
      exit 1
      ;;
esac
