#!/bin/bash
usage () {
  cat << EOF
  Use this script to delete a vserver config file from our cluster
  usage : ${0} -h hostname
EOF
}


while getopts :h: opt
do
  case ${opt} in
    h)  hostname=${OPTARG}
    ;;
    [?]) echo "${0} : option ${OPTARG} is not valid" >&2
         usage
         exit -1
    ;;
  esac
done

if [ -z ${hostname} ]
then
  usage
  exit -2
fi

svn rm dist/nodes/xen-1-cbv1/etc/xen/${hostname}.cfg
DOM0="xen-1-cbv1 xen-1-ext1 xen-2-cbv1 xen-2-ext1 xen-3-cbv1 xen-3-ext1"
for dom0 in $DOM0
do
  echo "suppression de /etc/xen/${hostname}.cfg sur $dom0"
  ssh $dom0 rm -rf /etc/xen/${hostname}.cfg
done

rake publish_prod
