#!/bin/sh

USAGE () {
  echo "use this script to promote a mysql slave"
}

USER_PASS="Eipha8si"
ROOT_PASS="Ikta2429"
USER="rep_slave"

NEW_MASTER=$(grep node /etc/ha.d/ha.cf | grep -v $(hostname) | sed 's/node[[:space:]]*//')

ACCESS="mysql --defaults-file=/etc/mysql/debian.cnf"

SLAVE_START="CHANGE MASTER TO MASTER_HOST=\"$NEW_MASTER\", MASTER_USER=\"$USER\", MASTER_PASSWORD=\"$USER_PASS\";"

NEW_SLAVE () {
  $ACCESS -e 'STOP SLAVE;'
  $ACCESS -e "$SLAVE_START"
  $ACCESS -e 'START SLAVE;'
}

NEW_SLAVE
exit 0
