#!/bin/sh
#
# Handle PostgreSQL failover
#

LEGAL_ACTIONS="(start|stop|status|usage|meta-data)"
OCF_SUCCESS=0
OCF_NOT_RUNNING=7
OCF_ERR_GENERIC=1

meta_data()
{
cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">

<resource-agent name="PGfailover">
<version>1.0</version>
<longdesc lang="en">This script manages PostgreSQL failover</longdesc>
<shortdesc lang="en">OCF Resource Agent compliant script.</shortdesc>
</resource-agent>
END
exit $OCF_SUCCESS
}

usage() {
  echo "usage: $0 $LEGAL_ACTIONS"
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

case $1 in
  start)
    touch /tmp/stopstandby
    exit $OCF_SUCCESS;;
  stop)
    rm /tmp/stopstandby 2>/dev/null
    exit $OCF_SUCCESS;;
  usage|help)
    usage
    exit OCF_SUCCESS;;
  status|monitor)
    if [ -f /tmp/stopstandby ]; then
      exit $OCF_SUCCESS
    else
      exit $OCF_NOT_RUNNING
    fi;;
  meta-data)
    meta_data;;
  *)
    echo "ERROR: Unknown operation: $1"
    usage
    exit 1;;
esac

