#!/bin/sh

echo "\n----------------------------------------------------
          Que souhaitez-vous faire ?
----------------------------------------------------\n
1 - Lancer un test
2 - Arreter un test
3 - Verifier la connectivité\n"
read action
case $action in
  1 )  echo "\n----------------------------------------------------
          Sur quel ISR (1 ou 2) ?
----------------------------------------------------\n"
       read numisr
       case $numisr in
         1 ) testencour=$(ssh 10.44.0.67 ps aux | grep iperf)
             if test -z "$testencour" ;
             then
              ssh 10.44.0.67 screen -d -m iperf -s -i 7200 -u ; ssh 10.44.0.67 ssh 169.254.0.2 screen -S screen2 -d -m iperf -c 169.254.0.1 -i 7200 -t 604800 -u -d -b 50M ; ssh 10.44.0.69 rm /var/www/mrtg/isr1/*.png /var/www/mrtg/isr1/*.log /var/www/mrtg/isr1/*.old /var/www/smokeping/Isr1_last_* ; echo "\nTest lancé sur l'ISR 1" ; echo "URL pour suivre le déroulement : http://supervision-isr-sav-1-por1/mrtg/isr1/ \n" 
             else
              echo "\nATTENTION : Des tests sont deja en cours"
              echo "Veuillez les arreter avant de demarrer un nouveau test\n"
            fi ;;
        2 ) testencour=$(ssh 10.44.0.68 ps aux | grep iperf)
             if test -z "$testencour" ;
             then
              ssh 10.44.0.68 screen -d -m iperf -s -i 7200 -u ; ssh 10.44.0.68 ssh 169.254.1.2 screen -S screen2 -d -m iperf -c 169.254.1.1 -i 7200 -t 604800 -u -d -b 50M ; ssh 10.44.0.69 rm /var/www/mrtg/isr2/*.png /var/www/mrtg/isr2/*.log /var/www/mrtg/isr2/*.old /var/www/smokeping/Isr2_last_* ; echo "\nTest lancé sur l'ISR 2" ; echo "URL pour suivre le déroulement : http://supervision-isr-sav-1-por1/mrtg/isr2/ \n" 
             else
              echo "\nATTENTION : Des tests sont deja en cours"
              echo "Veuillez les arreter avant de demarrer un nouveau test\n"
            fi ;;
         *) echo "Valeur incorrecte. Merci d'indiquer 1 ou 2"
       esac ;;
  2 ) echo "\n----------------------------------------------------
          Sur quel ISR (1 ou 2) ?
----------------------------------------------------\n"
       read numisr
       case $numisr in
         1 ) testencour=$(ssh 10.44.0.67 ps aux | grep iperf)
             if test -z "$testencour" ;
             then
              echo "Aucun test en cours sur cette ISR" 
             else
              ssh 10.44.0.67 killall iperf ; ssh 10.44.0.67 ssh 169.254.0.2 killall iperf ; echo "\nTest terminé. Merci de relancer ce script pour démarrer un nouveau test"
             fi ;;
         2 ) testencour=$(ssh 10.44.0.68 ps aux | grep iperf)
             if test -z "$testencour" ;
             then
              echo "Aucun test en cours sur cette ISR"
             else
              ssh 10.44.0.68 killall iperf ; ssh 10.44.0.68 ssh 169.254.1.2 killall iperf ; echo "\nTest terminé. Merci de relancer ce script pour démarrer un nouveau test"
             fi ;;
         * ) echo "Valeur incorrecte. Merci d'indiquer 1 ou 2"
        esac ;;
  3 ) echo "\n----------------------------------------------------
              Sur quel ISR (1 ou 2) ?
----------------------------------------------------\n"
      read numisr
      case $numisr in
        1 ) ssh 10.44.0.67 ping -c 4 169.254.0.1 ;;
        2 ) ssh 10.44.0.68 ping -c 4 169.254.1.1 ;;
        3 ) echo "Valeur incorrecte. Merci d'indiquer 1 ou 2";; 
      esac ;;
  *) echo "\nOn t'as dis 1 - 2 ou 3 ...";;
esac 
