use opensips;
drop trigger rr_D200911200001_loc_delete;
drop trigger rr_D200911200001_loc_update;
drop trigger rr_D200911200001_loc_insert;
drop trigger rr_D200911200001_loc_sequence;
DROP TRIGGER IF EXISTS rr_location_sequence;
DROP TRIGGER IF EXISTS rr_location_insert;
DROP TRIGGER IF EXISTS rr_location_update;
DROP TRIGGER IF EXISTS rr_location_delete;
DROP TABLE IF EXISTS rr_logged_events;
DROP TABLE IF EXISTS rr_pending_changes;
DROP TABLE IF EXISTS rr_running_flags;
DROP TABLE IF EXISTS rr_sequences;
