#!/bin/sh
### BEGIN INIT INFO
# Provides:       rubyrep
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    rubyrep
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
LOADER=/usr/bin/ruby1.8
DAEMON=/usr/bin/rubyrep
NAME=rubyrep
PIDFILE=/var/run/$NAME.pid
DESC=Rubyrep
SCRIPTNAME=/etc/init.d/$NAME
CONFIGFILE=/etc/rubyrep/rubyrep.conf

DAEMON_OPTS=" replicate -c $CONFIGFILE"

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions


case "$1" in
    start)
      #  if ps -aef | grep ruby1 | grep rubyrep ; then
      #    echo "Already running $DESC : restarting ..."
      #    kill -9 `ps -aef | grep $CONFIGFILE | grep -v grep | awk '{print $2}'`
      #  fi
       
        log_daemon_msg "Starting $DESC" $NAME
        if ! start-stop-daemon --start -u root -c root -m --quiet -b  --pidfile $PIDFILE --exec $LOADER $DAEMON -- $DAEMON_OPTS
        then
            log_end_msg 1
        else
            log_end_msg 0
        fi
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" $NAME
        if start-stop-daemon --quiet --stop -u root -m --oknodo  \
            --pidfile $PIDFILE 
        then
            rm -f $PIDFILE
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    restart)
        $0 stop
        test -r  $PIDFILE && while pidof rubyrep | \
            grep -q `cat $PIDFILE 2>/dev/null` 2>/dev/null ; do sleep 1; done
        $0 start
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0


