#!/bin/sh

USAGE () {
  echo "use this script to promote a rsyslog master"
}

MASTER=$(grep node /etc/ha.d/ha.cf | grep -v $(hostname) | sed 's/node[[:space:]]*//')
#USER_PASS="Eipha8si"
#USER="rep_slave"
#ACCESS="mysql --defaults-file=/etc/mysql/debian.cnf"

READ_ALL () {
  $ACCESS -e 'SHOW PROCESSLIST;' | grep -o "Has read all relay log"
}

NEW_MASTER () {
  /etc/init.d/rsyslog stop
  /etc/init.d/rsyslog start
#  $ACCESS -e 'STOP SLAVE IO_THREAD;'
#  $ACCESS -e 'STOP SLAVE; RESET MASTER;'
  
}

#SLAVE_START="CHANGE MASTER TO MASTER_HOST=\"$MASTER\", MASTER_USER=\"$USER\", MASTER_PASSWORD=\"$USER_PASS\";"

NEW_SLAVE () {
  /etc/init.d/rsyslog stop
#  $ACCESS -e 'STOP SLAVE;'
#  $ACCESS -e "$SLAVE_START"
#  $ACCESS -e 'START SLAVE;'
#  /etc/init.d/mysql restart
#  /opt/local/bin/promote_slave
  /usr/sbin/rsyslogd -c3 -f -x /opt/local/etc/rsyslog.conf
}

case $1 in
  start) NEW_MASTER;;
  stop)  NEW_SLAVE;;
  *)     USAGE;;
esac

