#!/bin/bash
# Ce script est destiné à créer un lv et a l'exporter via iscsi


data="data"

# Trouver sur quel vg nous avons le plus d'espace disponible
#vg_name () {
#  data0_size=$(vgs  --units G | grep data0 | awk '{print $7}' | sed 's/\..*G$//')
#  data1_size=$(vgs  --units G | grep data0 | awk '{print $7}' | sed 's/\..*G$//')
#
#  if [ $(expr $data0_size - $data1_size)  -gt 0 ]
#  then
#    data="data0"
#  else
#    data="data0"
#  fi
#}

get_tid () {
  numbers=$(cat /proc/net/iet/volume | grep "$name\$" | grep -Eo 'tid:[0-9]{1,3}' | sed 's/tid://' | sort -n)
  tid=$numbers
#  current=0
#  for number in $numbers
#  do
#    let current++
#    # if we find an unused number, we use it
#    if [ $number != $current ]
#    then
#      tid=$current
#      break
#    else
#      # else we add one to the last number
#      tid=$(expr $current + 1)
#    fi
#  done
}

test_target () {
  cat /proc/net/iet/volume | grep -o -E "$name$"
  if [ $? -eq 0 ]
  then
    echo "La target est deja exportee"
    exit -2
  fi
}


create_lv () {
#  vg_name
  /sbin/lvdisplay /dev/$data/$name > /dev/null 2>&1
  if [ $? -ne 0 ]
  then
    lvcreate -n $name -L ${size}G $data
  else
    echo "le volume $name existe deja"
    exit -3
  fi
  e2label /dev/$data/$name $name
}

export_target () {
  data=$(lvs | grep $name | awk '{print $2}')
  ietd="/etc/iet/ietd.conf"
  #tid=$(expr $(cat /proc/net/iet/volume | grep -Eo 'tid:[0-9]+' | sed s/tid:// | sort -n | tail -n 1) + 1)
  ietadm --op new --tid=0 --params Name=iqn.2008-07.fr.alphalink:storage.$name
  sleep 1
  get_tid
  ietadm --op new --tid=$tid --lun=0 --params Path="/dev/$data/$name",Type=fileio
  echo "Target iqn.2008-07.fr.alphalink:storage.$name" >> $ietd 
  echo -e "\tImmediateData yes" >> $ietd
  echo -e "\tLun 0 Path=/dev/$data/$name,Type=fileio" >> $ietd
}

create_export_target () {
  test_target
  create_lv
  export_target
}

delete_target_lv () {
  ietd="/etc/iet/ietd.conf"
  tid=$(cat /proc/net/iet/volume | grep $name | grep -Eo "tid:[0-9]*" | sed s/tid://)
  data=$(lvs | grep $name | awk '{print $2}')
  ietadm --op delete --tid=$tid
  sed -ie "/Target.*${name}/,/Lun.*${name}/d" $ietd
  echo "The LV $name is going to be erased"
  echo "All data will be destroy"
  echo "Do you really want destroy it ? y/n"
  read answer
  if [ $answer == 'y' ]
  then
    test -b /dev/$data/$name
    if [ $? == 0 ]
    then
      lvremove --force /dev/$data/$name > /dev/null 2>&1
    else
      echo "The device /dev/$data/$name doesn't exist"
    fi
  fi
}

usage () {
  echo "$0 -n name -s size [-c] [-d] [-e]"
  echo "  -v Specify lvm vg to use (default to data)"
  echo "  -c create lv and export it via iscsi"
  echo "  -d unexport and destroy lv, ALL DATA WILL BE LOSE"
  echo "  -e export lv via iscsi, the lv must exist"
  exit -1
}

while getopts :n:s:vcde opt
do
  case $opt in
    n) name=$OPTARG
         if [ -z $name ]
         then
           echo "Vous devez specifier un nom d'hote"
           usage
           exit -4
         fi
    ;;
    s) size=$OPTARG;;
    v) data=$OPTARG;;
    c) create_export_target;;
    d) delete_target_lv;;
    e) export_target;;
    [?]) usage;;
  esac
done

if [ -z $1 ]; then
  usage
fi
