#!/bin/sh

USAGE () {
  echo "use this script to promote a rsyslog master"
}

MASTER=$(grep node /etc/ha.d/ha.cf | grep -v $(hostname) | sed 's/node[[:space:]]*//')

NEW_MASTER () {
  /etc/init.d/rsyslog stop
  /etc/init.d/rsyslog start
}


NEW_SLAVE () {
  /etc/init.d/rsyslog stop
  /usr/sbin/rsyslogd -c3 -f -x /opt/local/etc/rsyslog.conf
}

case $1 in
  start) NEW_MASTER;;
  stop)  NEW_SLAVE;;
  *)     USAGE;;
esac

